### PR TITLE
Remove attack example from modifier_reentrancy_fixed

### PR DESCRIPTION
**Pull request by s0b0lev**

### CODE REVIEW

**Comment by wuestholz** [comment]
@s0b0lev If I remember correctly, the analysis should run on contract `ModifierEntrancy`.

**Comment by s0b0lev** [comment]
Good point @wuestholz , thanks. Updated.

**Comment by wuestholz** [comment]
@s0b0lev Sorry for not noticing earlier, but I think the same changes (i.e., drop `attack` contract and run on `ModifierEntrancy`) should be applied to the vulnerable version: https://github.com/SmartContractSecurity/SWC-registry/tree/master/test_cases/solidity/reentracy/modifier_reentrancy.

**Comment by s0b0lev** [comment]
@wuestholz definitely! I will do it in another pr

**Pull request merged**
