### PR TITLE
Fix typos, Improve grammar

### PR DESCRIPTION
**Pull request by portdeveloper**

### CODE REVIEW

**Comment by chaals** [comment]
This Repo hasn't been actively maintained for a couple of years, but occasionally it gets some minor stuff cleaned up. IMHO (and I can merge a PR) this one would qualify as a simple useful claenup, if you want to re-open it.

Since the Merge things have changed very slightly (we don't have miners, but validators, and they operate under slightly different circumstances. That could be cleaned up in a subsequent edit.

**Comment by portdeveloper** [comment]
Do you think it makes sense to maybe get things running once again?

**Review by chaals — APPROVED** [review]
This is a net improvement.

**Comment by BubblyOrca** [comment]
Is it possible for PRs to still be reviewed and merged to this repo? I noticed the activity under this thread.

**Pull request merged**
