### PR TITLE
Fix several test cases and add bytecode offsets

### LINKED ISSUE #116: Unclear testcase for SWC-112
Hi,

[SWC-112](https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-112) description states that you should not call untrusted contract with delegatecall. Its short description is: `Delegation sets target address in delegatecall() from user input`

The testcase [test_cases/delegate_call_to_untrusted_callee/delegate.sol](https://github.com/SmartContractSecurity/SWC-registry/blob/86118bc99a2d5fee639c5a8b47f6214ae1236ad9/test_cases/delegate_call_to_untrusted_callee/delegate.sol) is a bit ambigious and does not seem to fit really the description.

Here you call a destination that was added at construction. The destination cannot be changed,so it should be fine:

https://github.com/SmartContractSecurity/SWC-registry/blob/86118bc99a2d5fee639c5a8b47f6214ae1236ad9/test_cases/delegate_call_to_untrusted_callee/delegate.sol#L27-L35

But the destination has a bug that allows anyone to become the owner:

https://github.com/SmartContractSecurity/SWC-registry/blob/86118bc99a2d5fee639c5a8b47f6214ae1236ad9/test_cases/delegate_call_to_untrusted_callee/delegate.sol#L17-L19

The testcase for SWC-112 should not be rather showing an example where anyone can change the delegatecall destination?

### PR DESCRIPTION
**Pull request by b-mueller**
Fixes #116

### CODE REVIEW

**Comment by thec00n** [comment]
Why is  test_cases/delegate_call_to_untrusted_callee/proxy_pattern_false_positive removed?

**Comment by b-mueller** [comment]
> Why is test_cases/delegate_call_to_untrusted_callee/proxy_pattern_false_positive removed?

I found it to be a confusing example and not a great fit for this category (I would have moved it so SWC-105) but on second thought it's actually not so bad.

I improved the description a bit and added a more trivial "fixed" example.

**Comment by b-mueller** [comment]
Location info in proxy.yaml should be the following IMO:

```
  - bytecode_offsets: [337]
  - line_numbers: [12]
```

(the location of the delegatecall)?

**Comment by thec00n** [comment]
Yes, I was about to fix that.

**Pull request merged**
