### PR TITLE
Add SWC-133: Code smells

### PR DESCRIPTION
**Pull request by nbanmp**

### CODE REVIEW

**Comment by thec00n** [comment]
I would like to encourage you to split code smells up in different categories. This is in line with what we have done in the past and SWC-100 or SWC-108 are examples of that. You should also have a description that explains that nature of the category and a remediation. With a higher granularity it's easier to manage those SWC categories as there should be less overlap.

**Comment by nbanmp** [comment]
@thec00n Our thought process for this was to have a sort of catch-all SWC for automated tools when reporting non-vulnerabilities, but issues that are still relevant to security. By not breaking this up, we make it easier for tool developers to report issues that otherwise would not have its own SWC entry.

We can create additional SWC entries for specific code smells, but we still think that having a catch-all would be beneficial. I can update the description to define SWC-133 as "code smells not covered by other SWCs"

**Comment by thec00n** [comment]
`sort of catch-all SWC`
I don't see why it should not be possible to articulate for any type of security related issue (unless maybe it's really exotic) why it should be avoided and what you can do to not have that issue, find references (other people who also think it's bad idea to do what you are describing) and link it back to general software security (CWE). 

A catch all is bad because then you don't really need to do articulate those things and that's kind of what the SWC is about.

**Comment by b-mueller** [comment]
A lot of these things don't have enough "meat" to warrant a separate entry. Unused code or an unused variable isn't really something you can write about. From the tool builder's side it's a lot of overhead to add a new entry for these minor informational things.

I do think that a list of concrete things should be described in this SWC (each with a short paragraph). Later we can also add language-specific ones?

**Comment by thec00n** [comment]
From my experience by far the most time consuming work is adding test cases. Adding a description why unused code or other more quality kind of things are undesirable should be easy. It does not need to be an essay, short and to the point is good.

If you are proposing to add a `bucket of things` category to the registry then please consider the existing categories and if some of them should be move as well.

**Comment by nbanmp** [comment]
We'll separate out code smells.

**Pull request closed without merging**
