### PR TITLE
Add new entry (SWC-130) - Unicode RTLO character abuse

### PR DESCRIPTION
**Pull request by shshzi**
We will be adding a link to a blog post where we describe the issue in more detail, first wanted to reserve an SWC number so it could be referenced elsewhere

### CODE REVIEW

**Comment by shshzi** [comment]
Does it fail because the "Relationships" section is empty?

**Comment by thec00n** [comment]
Yes. Also please add at least one test case to illustrate the issue. Thanks.

**Comment by shshzi** [comment]
Done. Thanks.

**Comment by shshzi** [comment]
@thec00n - can we merge this? thnx

**Pull request merged**
