### PR TITLE
Added a few references for related learning resources

### PR DESCRIPTION
**Pull request by pi3ch**
A few reference links to related fix me challenges. A great way to fully understand some of these SWC. Minor clean ups.

### CODE REVIEW

**Comment by lord-pendragon** [comment]
@PatrickAlphaC is this repo still maintained?
Any updates on getting this PR through?

**Comment by PatrickAlphaC** [comment]
Looks like it's not. Someone should fork it and keep it going.

**Comment by PatrickAlphaC** [comment]
I don't have any insight to this repo.

**Comment by lord-pendragon** [comment]
That's a shame @pi3ch what are your thoughts on forking it for continuity?

**Comment by thec00n** [comment]
see https://t.me/c/1372269197/58874

**Comment by chaals** [comment]
Given people can't directly follow the links, I am not going to merge this, so closing. (Linking to the entry point might make sense, but probably more relevant from a maintained resource)

**Pull request closed without merging**
