### PR TITLE
Improvement of test case configs

### PR DESCRIPTION
**Pull request by s0b0lev**
@thec00n here is some proposals after the chat with @wuestholz :
- out-of-bounds-exception.sol: consider these to be assertion violations since this is how they are compiled 
- overflow_single_tx.sol: I would consider there to be 3 more overflows 

What do you think?

@wuestholz could describe more details for **overflow_single_tx.sol**?

### CODE REVIEW

**Comment by wuestholz** [comment]
For out-of-bounds-exception.sol it might make sense to add the following issues since on the bytecode-level array-out-of-bounds is encoded as assertions:
- SWC-110 @ 259:1:0 (0x6851506d5832e8f5286cfaa3eb0181f3934fd480096d583285a0b81d82df3c89)
- SWC-110 @ 226:1:0 (0x6851506d5832e8f5286cfaa3eb0181f3934fd480096d583285a0b81d82df3c89)

For overflow_single_tx.sol it might make sense to add the following issues since there are overflows happening (even though they don't affect storage or anything else that can be observed by the users such as return values):
- SWC-101 @ 511:1:0 (0xff96d6431ca052ba7228a96a7d27b0adc1f493a2c460cc8a44b2565b9ef14840)
- SWC-101 @ 456:1:0 (0xff96d6431ca052ba7228a96a7d27b0adc1f493a2c460cc8a44b2565b9ef14840)
- SWC-101 @ 542:1:0 (0xff96d6431ca052ba7228a96a7d27b0adc1f493a2c460cc8a44b2565b9ef14840)

@thec00n and I had discussed the changes for overflow_single_tx.sol briefly and one option was to simply drop those functions from the benchmark since they don't add much.

**Comment by thec00n** [comment]
Hey @wuestholz @s0b0lev I am proposing to remove `overflow_single_tx.sol` as the 3 cases that change state are captured by other test cases for SWC-101 issues. 

For test_cases/solidity/assert_violations/out-of-bounds-exception/out-of-bounds-exception.yaml I think @wuestholz proposition makes sense.

**Comment by wuestholz** [comment]
@thec00n Sounds good. Thanks!

**Comment by s0b0lev** [comment]
@thec00n @wuestholz am I right that all changes were adopted? Do we have anything to do here before merging this branch?

**Comment by thec00n** [comment]
Remove public accessor for test_cases/solidity/assert_violations/out-of-bounds-exception/out-of-bounds-exception.yaml, update JSON and config. Merging this PR.

**Pull request merged**
