### PR TITLE
An example where indexing can legitimately raise an exception...

### PR DESCRIPTION
**Pull request by rocky**
This is a slight variation of assert_violations/out-of-bounds-exception_1.sol

### CODE REVIEW

**Comment by b-mueller** [comment]
Explicitly setting the length of the array doesn't make a difference for this test case, so this is essentially the same as This is the same example as [out-of-bounds-exception.sol](https://github.com/SmartContractSecurity/SWC-registry/blob/master/test_cases/assert_violations/out-of-bounds-exception.sol).

With the dynamically sized array the exception can be "fixed" the following way:

```
pragma solidity ^0.4.19;

contract OutOfBoundsException {

	uint256[] public array;

	function getArrayElement(uint256 idx) returns (uint256) {
		require (idx < array.length);
		return array[idx];
	}
}
```
Whereas in your sample:

```
pragma solidity ^0.4.19;

contract OutOfBoundsException {

	uint256[8] public array;

	function getArrayElement(uint256 idx) returns (uint256) {
		require (idx <8);
		return array[idx];
	}
}
```

The only question is if we consider the lack of a `require()` check an issue or not. Personally I don't think that the lack of an explicit `require()` constitutes a security issue.

**Comment by rocky** [comment]
> The only question is if we consider the lack of a require() check an issue or not. 

If it not an issue, then by removing it in `assert_violations/out-of-bounds-exception.sol` the case is made more forcefully that there should be no error, and that micro benchmark is more micro.

**Comment by b-mueller** [comment]
What do you mean by "removing the indexing"?

Currently the intention of this benchmark is to show that while there are two reachable exceptions, those should *not* be reported. This is expressed by the YAML file:

```
description: "Exceptions triggered by out-of-bounds array (not an explicit assert violation)."
issues:
- id: "SWC-110"
  count: 0
```

Which basically says "you should look for assert violations in this file but not find any, and in particular you shouldn't mistake the out-of-bounds array indexing for assert violations."

**Comment by rocky** [comment]
> Explicitly setting the length of the array doesn't make a difference for this test case

I might misunderstand how Solidity works. If it is the case that `uint256[] public array` allows any uint256 value as an index, then clearly there is no way to get an indexing error by indexing using a uin256 variable. However if uint256[8] can not be subseqently changed, then there is the possibility of an indexing error. 

Yes, I realize that solc currently emits a check. However wa that true for _all_ versions of solc?

**Comment by b-mueller** [comment]
`uint256[] public array allows any uint256 value as an index, then clearly there is no way to get an indexing error by indexing using a uin256 variable.`

I see what you mean. Dynamically sized arrays store their own length and you have to extend them with `array.push()`, you can't access arbitrary indices unless they're < array.length. That's the cause of the exception here.

`removing the indexing in assert_violations/out-of-bounds-exception.sol, the case is made more forcefully that there should be no error, and that micro benchmark is more micro.`

We can do that if you want but I don't think it really changes the forcefulness of our case :)

**Comment by b-mueller** [comment]
On a side note I just made an interesting observation:

```
pragma solidity ^0.4.19;

contract OutOfBoundsException {

	uint256[] public array;

	constructor() {
		// Underflow length to MAX_INT
		array.length -= 1;
	}

	function getArrayElement(uint256 idx) returns (uint256) {
		return array[idx];
	}
}
```

I would actually expect Mythril *not* to report an exception here because array.length is set to MAX_INT in the constructor, so it should not be possible to reference an invalid element. Mythril does report it however:

```
$ $MYTH -x  test1.sol 
==== Integer Underflow ====
Type: Warning
Contract: OutOfBoundsException
Function name: constructor
PC address: 28
A possible integer underflow exists in the function `constructor`.
The subtraction may result in a value < 0.
--------------------
In file: test1.sol:8

array.length -= 1

--------------------

==== Exception state ====
Type: Informational
Contract: OutOfBoundsException
Function name: getArrayElement(uint256)
PC address: 226
A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. 
--------------------
In file: test1.sol:12

array[idx]

--------------------

==== Exception state ====
Type: Informational
Contract: OutOfBoundsException
Function name: array(uint256)
PC address: 259
A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. 
--------------------
In file: test1.sol:5

uint256[] public array

--------------------

```

**Comment by rocky** [comment]
> We can do that if you want but I don't think it really changes the forcefulness of our case :)

But it _does_ make it smaller and doesn't confuse people (like it appearently did for both me and @maurelian) and appearently to some extend you since it wasn't obvious that the `array[idx]` was totally safe. 

That said I can see a case made for more realistic contracts, although I'm not sure either is realistic.

**Comment by b-mueller** [comment]
Addin a better explanation in the comments might help also? Maybe I'll do that.

**Comment by thec00n** [comment]
There was some initial discussions regarding the example see https://github.com/SmartContractSecurity/SWC-registry/pull/33. While I think the example from @b-mueller is a legitimate use to test that a specific variant is not mixed up with another variant. Find 0 instances of assert violations in test sample is correct. Also I think that the out of bounds example is its own variant.

**Comment by rocky** [comment]
@thec00n : Earlier @b-mueller explained and we got into the weeds of why solidity creates effectively an `assert` in the code for `uint256[] public array` and it looks like, indeed, the compiler should be doing that, but only when the public array is accessed via an accessor. This is not the case in `out-of-bound-exception.sol`, but the compiler is not smart enough to detect that.

However in this situation, the _other_ effective `assert` via `array[idx]` is also legitimate and can be raised in this particular test case.

**Comment by rocky** [comment]
You point out that it is a potential problem

It could be: 

* a type mismatch
* an explicit index check (`if`) with appropriate action if violated
* a `require` which returns gas
* specifying an invariant to mythril platform which allows this to prove/check that this can't occur.

**Comment by thec00n** [comment]
@b-mueller @rocky is there a conclusion on if this PR is going to be merged?

**Comment by rocky** [comment]
I have made my case above. But I leave to @b-mueller to make the final decision.

**Comment by b-mueller** [comment]
> Find 0 instances of assert violations in the test sample is correct. Having said that I also think that the out of bounds example is its own variant.

I agree with this assessment. If we think that out-of-bounds array access should be reported as a weakness, it needs to become its own SWC variant (it's not an example of explicit assert violation).

I'll therefore close this PR.

**Pull request closed without merging**
