### PR TITLE
Invoke correct contract for BecToken

### PR DESCRIPTION
**Pull request by s0b0lev**

### CODE REVIEW

**Comment by wuestholz** [comment]
I think the bytecode location should also be updated here. This is the one I get for the overflow: SWC-101 @ 1587:1:0 (0x9ff018873b1dce60dc9e4aaeda9b4e1f3f215e08c4070f0ef2cc24268fbeb493)

In addition, I get an assertion violation (possibly due to the safemath operations): SWC-110 @ 4229:1:0 (0x9ff018873b1dce60dc9e4aaeda9b4e1f3f215e08c4070f0ef2cc24268fbeb493)

**Comment by s0b0lev** [comment]
@thec00n how should we act with this:

```
In addition, I get an assertion violation (possibly due to the safemath operations): SWC-110 @ 4229:1:0 (0x9ff018873b1dce60dc9e4aaeda9b4e1f3f215e08c4070f0ef2cc24268fbeb493)

Maybe that should be added as well or we should turn those asserts into requires.
```

Do we need one more issue definition for that test case?

**Comment by wuestholz** [comment]
@s0b0lev Yes, if you prefer to not change those asserts to `require` I would add a separate issue for the assertion violation.

**Comment by s0b0lev** [comment]
kk, @wuestholz I changed them, please merge PR if everything is ok

**Comment by wuestholz** [comment]
@wuestholz Let me run Harvey on the new bytecode in case the location changed. I'll ping you once that's done.

**Comment by wuestholz** [comment]
@s0b0lev I still get both issues with Harvey. Did you update the JSON output after recompiling the changed code?

**Comment by s0b0lev** [comment]
@wuestholz sorry, forgot about it

**Pull request merged**
